### ISSUE TITLE
php 无法build

### ISSUE THREAD

**Issue by jg101110** [Qihoo360/qbusbridge#1]
../cxx/src/qbus_record_msg.h:6:30: fatal error: log4cplus/logger.h: No such file or directory
compilation terminated.
In file included from ../cxx/src/qbus_consumer.cc:3:0:
../cxx/util/logger.h:4:30: fatal error: log4cplus/logger.h: No such file or directory
compilation terminated.
../cxx/src/qbus_producer.cc:9:47: fatal error: thirdparts/librdkafka/src/rdkafka.h: No such file or directory
compilation terminated.
In file included from ../cxx/src/qbus_config.cc:1:0:
../cxx/src/qbus_config.h:6:41: fatal error: boost/property_tree/ptree.hpp: No such file or directory
compilation terminated.
In file included from ../cxx/src/qbus_helper.cc:1:0:
../cxx/src/qbus_helper.h:8:47: fatal error: thirdparts/librdkafka/src/rdkafka.h: No such file or directory
compilation terminated.
In file included from ../cxx/util/logger.cc:1:0:
../cxx/util/logger.h:4:30: fatal error: log4cplus/logger.h: No such file or directory
compilation terminated.
In file included from ../cxx/src/qbus_consumer_imp.cc:1:0:
../cxx/src/qbus_consumer_imp.h:9:47: fatal error: thirdparts/librdkafka/src/rdkafka.h: No such file or directory
compilation terminated.
qbus_wrap.cxx:747:18: fatal error: zend.h: No such file or directory

**Comment by DavidLiuXh** [comment]
先安装 log4cplus这个依赖，再试一下

**Comment by jg101110** [comment]
这个貌似是缺少类似于 log4cplus/logger.h之类的文件，我是在alpine系统中编译的。能否提供一下这个log4cplus适配版本源码比较好，从项目中直接下载的一些文件夹是空的比如：librdkafka；还有我想确认一下，这个库是否可以真的就解决php连接kafka开闭的性能问题？php进程在任务处理完之后是会销毁对象的，再次请求又是新的对象是否还会重新创建链接？

**Comment by DavidLiuXh** [comment]
1. log4cplus我们使用的就是官方版本：https://sourceforge.net/projects/log4cplus/files/log4cplus-stable/1.2.1/
2. librdkafka是我们主要依赖的底层库，采用git submoudle的方式, 使用 git clone --recursive https://github.com/Qihoo360/kafkabridge.git 来clone即可同时获取librdkafka;
3. 针对php的优化我们主要是用在php-fpm这种场景下，fpm进程不重启会复用连接，这个复用的连接是针对同一个集群.

**Comment by wangxiqunlucky** [comment]
> 1. log4cplus我们使用的就是官方版本：https://sourceforge.net/projects/log4cplus/
> 2. librdkafka是我们主要依赖的底层库，采用git submoudle的方式, 使用 git clone --recursive https://github.com/Qihoo360/kafkabridge.git 来clone即可同时获取librdkafka;
> 3. 针对php的优化我们主要是用在php-fpm这种场景下，fpm进程不重启会复用连接，这个复用的连接是针对同一个集群.

您好,我也遇到了类似build不成功问题, centos 7 环境下,请问如何修改 php/TopMakefile 文件的
CPP_DLLIBS = #-L/usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.7.2 \
             -L/usr/local/lib -lg++ -lstdc++ -lgcc
配置项?

**Comment by DavidLiuXh** [comment]
@wangxiqunlucky 用的是build.sh脚本编译的吗？

**Comment by wangxiqunlucky** [comment]
> @wangxiqunlucky 用的是build.sh脚本编译的吗？

是,脚本编译中好像相当多的参数都需要修改. 比如boost版本号等. librdkafka使用的是您上面提供的 git -recusive 获取的.

**Comment by mr-wing** [comment]
Dependencies: liblog4cplus, boost, swig-3.0.12, cmake
php下的编译可以看下./build -h

**Comment by DavidLiuXh** [comment]
我们调整了php的编译脚本和README，暂时先关闭这个issue.
