### ISSUE TITLE
内存一直在增加

### ISSUE THREAD

**Issue by luolaifa000** [Qihoo360/qbusbridge#11]
qbus::QbusProducer triggerQbusProducer;
string dispatchTopic = DISPATCH_CONFIG_NAME;
this->QbusProducerInit(triggerQbusProducer, dispatchTopic);
this->QbusProducerData(triggerQbusProducer, sendData);
this->QbusProducerDeinit(triggerQbusProducer);

用法是这样的，每个协程都会调一次

**Comment by BewareMyPower** [comment]
建议 C/C++ 的话直接去用 librdkafka 吧，基本上这个项目没人维护了。
