### ISSUE TITLE
作者你好 ,windows 7 下使用gitbash 执行 ./build_librdkafka.sh 命令无法编译报错,请问是什么原因导致呢?

### ISSUE THREAD

**Issue by dippac** [Qihoo360/qbusbridge#6]
$ ./build_librdkafka.sh
make[1]: Entering directory 'C:/Users/win7/kafkabridge/cxx/thirdparts/librdkafka/tests'
rm -f *.test 0039-event.o 0076-produce_retry.o 0028-long_topicnames.o 0031-get_offsets.o 0051-assign_adds.o 0074-producev.o 0011-produce_batch.o 0004-conf.o 0021-rkt_destroy.o 0081-admin.o 0013-null-msgs.o 0068-produce_timeout.o 0038-performance.o 0046-rkt_cache.o 0008-reqacks.o 0036-partial_fetch.o 0073-headers.o 0020-destroy_hang.o 0035-api_version.o 0006-symbols.o 0092-mixed_msgver.o 0084-destroy_flags.o 0086-purge.o 0050-subscribe_adds.o 0069-consumer_add_parts.o 0044-partition_cnt.o 0030-offset_commit.o 0029-assign_offset.o 0026-consume_pause.o 0034-offset_reset.o 0018-cgrp_term.o 0000-unittests.o 0094-idempotence_msg_timeout.o 0055-producer_latency.o 0003-msgmaxsize.o 0083-cb_event.o 0017-compression.o 0093-holb.o 0052-msg_timestamps.o 0002-unkpart.o 0040-io_event.o 0037-destroy_hang_local.o 0072-headers_ut.o 0025-timers.o 0048-partitioner.o 0089-max_poll_interval.o 0012-produce_consume.o 0047-partial_buf_tmout.o 0049-consume_conn_close.o 0007-autotopic.o 0014-reconsume-191.o 0022-consume_batch.o 0001-multiobj.o 0033-regex_subscribe.o 0077-compaction.o 0062-stats_event.o 0019-list_groups.o 0091-max_poll_interval_timeout.o 0088-produce_metadata_timeout.o 0080-admin_ut.o 0045-subscribe_update.o 0005-order.o 0041-fetch_max_bytes.o 0043-no_connection.o 0015-offset_seeks.o 0056-balanced_group_mt.o 0042-many_topics.o 0075-retry.o 0064-interceptors.o 0090-idempotence.o 0079-fork.o 0066-plugins.o 0057-invalid_topic.o 0061-consumer_lag.o 0070-null_empty.o 0053-stats_cb.o 0082-fetch_max_bytes.o 0095-all_brokers_down.o 8000-idle.o 0063-clusterid.o 0058-log.o 0078-c_from_cpp.o 0085-headers.o 0065-yield.o 0060-op_prio.o 0067-empty_topic.o 0054-offset_time.o 0059-bsearch.o test.o testcpp.o tinycthread.o tinycthread_extra.o rdlist.o sockem.o sockem_ctrl.o merged
C:/Program Files/Git/mingw64/bin/make -C interceptor_test clean
make[2]: Entering directory 'C:/Users/win7/kafkabridge/cxx/thirdparts/librdkafka/tests/interceptor_test'
rm -f interceptor_test.o interceptor_test.d
rm -f interceptor_test*.a interceptor_test.1 interceptor_test \
        interceptor_test.lds
make[2]: Leaving directory 'C:/Users/win7/kafkabridge/cxx/thirdparts/librdkafka/tests/interceptor_test'
make[1]: Leaving directory 'C:/Users/win7/kafkabridge/cxx/thirdparts/librdkafka/tests'
make[1]: Entering directory 'C:/Users/win7/kafkabridge/cxx/thirdparts/librdkafka/examples'
rm -f rdkafka_example rdkafka_performance rdkafka_example_cpp rdkafka_consumer_example rdkafka_consumer_example_cpp kafkatest_verifiable_client rdkafka_simple_producer rdkafka_idempotent_producer
make[1]: Leaving directory 'C:/Users/win7/kafkabridge/cxx/thirdparts/librdkafka/examples'
/usr/bin/sh: C:/Program: No such file or directory
/usr/bin/sh: C:/Program: No such file or directory
make: *** [Makefile:50: clean] Error 127
checking for OS or distribution... ok (mingw64_nt-6.1-7601)
checking for C compiler from CC env... failed
checking for gcc (by command)... failed
checking for clang (by command)... failed
checking for cc (by command)... failed (fail)
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... failed
checking for C++ compiler (clang++)... failed
checking for C++ compiler (c++)... failed (fail)
checking executable ld... failed (disable)
checking executable nm... failed (disable)
checking executable objdump... failed (disable)
checking executable strip... failed (disable)
checking for pkgconfig (by command)... failed
checking for install (by command)... ok
checking for PIC (by compile)... failed (disable)
checking for GNU-compatible linker options... failed
checking for OSX linker options... failed
checking for GNU linker-script ld flag... failed
checking for Solaris linker-script ld flag... failed (ignore)
checking for __atomic_32 (by compile)... failed
checking for __atomic_32_lib (by compile)... failed
checking for __sync_32 (by compile)... failed (disable)
checking for __atomic_64 (by compile)... failed
checking for __atomic_64_lib (by compile)... failed
checking for __sync_64 (by compile)... failed (disable)
checking for socket (by compile)... failed
checking for socket_nsl (by compile)... failed (fail)
parsing version '0x010001ff'... ok (1.0.1)
checking for librt (by compile)... failed
checking for libpthread (by compile)... failed (fail)
checking for c11threads (by compile)... failed (disable)
checking for libdl (by compile)... failed (disable)
checking for zlib (by compile)... failed (disable)
checking for zstd (by compile)... failed (disable)
checking for libm (by compile)... failed (disable)
checking for liblz4 (by compile)... failed (disable)
checking for rapidjson (by compile)... failed (disable)
checking for crc32chw (by compile)... failed (disable)
checking for regex (by compile)... failed (disable)
checking for strndup (by compile)... failed (disable)
checking for strerror_r (by compile)... failed (disable)
checking for pthread_setname_gnu (by compile)... failed (disable)
checking for nm (by env NM)... failed

###########################################################
###########################################################
###########################################################
 cc (WITH_CC)
    module: cc
    action: fail
    reason:
command 'cc --version' failed:
mklove/modules/configure.base: line 1692: cc: command not found

 cxx (WITH_CXX) C++ compiler (c++)
    module: cc
    action: fail
    reason:
command 'c++ --version' failed:
mklove/modules/configure.base: line 1692: c++: command not found

 socket_nsl ()
    module: socket
    action: fail
    reason:
compile check failed:
CC: CC
flags:
  -g -O2 -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpGztdD4.c -o _mkltmpGztdD4.c.o -lsocket -lnsl  :
mklove/modules/configure.base: line 1326: -g: command not found
source:
#include <sys/types.h>
#include <sys/socket.h>
#include <unistd.h>
void foo (void) {
   int s = socket(0, 0, 0);
   close(s);
}

 libpthread ()
    module: self
    action: fail
    reason:
compile check failed:
CC: CC
flags: -lpthread
  -g -O2 -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpL9265y.c -o _mkltmpL9265y.c.o   -lpthread:
mklove/modules/configure.base: line 1326: -g: command not found
source: #include <pthread.h>

sed: can't read /c/Users/win7/kafkabridge/cxx/thirdparts/librdkafka/config.h: No such file or directory
sed: can't read /c/Users/win7/kafkabridge/cxx/thirdparts/librdkafka/config.h: No such file or directory
sed: can't read /c/Users/win7/kafkabridge/cxx/thirdparts/librdkafka/config.h: No such file or directory
sed: can't read /c/Users/win7/kafkabridge/cxx/thirdparts/librdkafka/config.h: No such file or directory
./Makefile.config missing: please run ./configure
make: *** [mklove/Makefile.base:73: mklove-check] Error 1

**Comment by BewareMyPower** [comment]
kafkabridge是Linux C++库，不是跨平台的。gitbash只是有一些Linux下常用命令，并不能代表就能模拟Linux编译环境了。

**Comment by dippac** [comment]
CMake Warning (dev) at CMakeLists.txt:65 (ADD_LIBRARY):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "QBus" links to some libraries for which the linker must
  search:

    z, stdc++, pthread, rt, dl

  and other libraries with known full path:

    /usr/local/lib/liblog4cplus.so
    /home/csb-devops/Desktop/tom/kafkabridge/cxx/build/../thirdparts/librdkafka/src/librdkafka.a

  CMake is adding directories in the second list to the linker search path in
  case they are needed to find libraries from the first list (for backwards
  compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
  or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
  more information.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/csb-devops/Desktop/tom/kafkabridge/cxx/build
/usr/bin/cmake -H/home/csb-devops/Desktop/tom/kafkabridge/cxx/src -B/home/csb-devops/Desktop/tom/kafkabridge/cxx/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/csb-devops/Desktop/tom/kafkabridge/cxx/build/CMakeFiles /home/csb-devops/Desktop/tom/kafkabridge/cxx/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/csb-devops/Desktop/tom/kafkabridge/cxx/build'
make -f CMakeFiles/QBus.dir/build.make CMakeFiles/QBus.dir/depend
make[2]: Entering directory '/home/csb-devops/Desktop/tom/kafkabridge/cxx/build'
cd /home/csb-devops/Desktop/tom/kafkabridge/cxx/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/csb-devops/Desktop/tom/kafkabridge/cxx/src /home/csb-devops/Desktop/tom/kafkabridge/cxx/src /home/csb-devops/Desktop/tom/kafkabridge/cxx/build /home/csb-devops/Desktop/tom/kafkabridge/cxx/build /home/csb-devops/Desktop/tom/kafkabridge/cxx/build/CMakeFiles/QBus.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/csb-devops/Desktop/tom/kafkabridge/cxx/build'
make -f CMakeFiles/QBus.dir/build.make CMakeFiles/QBus.dir/build
make[2]: Entering directory '/home/csb-devops/Desktop/tom/kafkabridge/cxx/build'
[ 10%] Building CXX object CMakeFiles/QBus.dir/home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.o
/usr/bin/c++   -DQBus_EXPORTS -I/home/csb-devops/Desktop/tom/kafkabridge/cxx/src/. -I/home/csb-devops/Desktop/tom/kafkabridge/cxx/src/..  -std=c++11 -O3 -DNDEBUG -fPIC   -O2 -Wall  -o CMakeFiles/QBus.dir/home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.o -c /home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.cc
/home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.cc: In static member function 'static void LUtil::Logger::init(LUtil::Logger::LOG_LEVEL, const char*, bool)':
/home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.cc:40:10: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<log4cplus::Layout> layout(new log4cplus::PatternLayout(
          ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /usr/local/include/log4cplus/layout.h:39,
                 from /usr/local/include/log4cplus/appender.h:33,
                 from /usr/local/include/log4cplus/spi/appenderattachable.h:33,
                 from /usr/local/include/log4cplus/logger.h:36,
                 from /home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.h:4,
                 from /home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.cc:1:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
/home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.cc:47:39: error: no matching function for call to 'log4cplus::Appender::setLayout(std::auto_ptr<log4cplus::Layout>&)'
         fileAppender->setLayout(layout);
                                       ^
In file included from /usr/local/include/log4cplus/spi/appenderattachable.h:33:0,
                 from /usr/local/include/log4cplus/logger.h:36,
                 from /home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.h:4,
                 from /home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.cc:1:
/usr/local/include/log4cplus/appender.h:221:22: note: candidate: virtual void log4cplus::Appender::setLayout(std::unique_ptr<log4cplus::Layout>)
         virtual void setLayout(std::unique_ptr<Layout> layout);
                      ^
/usr/local/include/log4cplus/appender.h:221:22: note:   no known conversion for argument 1 from 'std::auto_ptr<log4cplus::Layout>' to 'std::unique_ptr<log4cplus::Layout>'
/home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.cc:57:16: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
           std::auto_ptr<log4cplus::Layout> layout(new log4cplus::PatternLayout(
                ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /usr/local/include/log4cplus/layout.h:39,
                 from /usr/local/include/log4cplus/appender.h:33,
                 from /usr/local/include/log4cplus/spi/appenderattachable.h:33,
                 from /usr/local/include/log4cplus/logger.h:36,
                 from /home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.h:4,
                 from /home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.cc:1:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
/home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.cc:61:46: error: no matching function for call to 'log4cplus::Appender::setLayout(std::auto_ptr<log4cplus::Layout>&)'
             consoleAppender->setLayout(layout);
                                              ^
In file included from /usr/local/include/log4cplus/spi/appenderattachable.h:33:0,
                 from /usr/local/include/log4cplus/logger.h:36,
                 from /home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.h:4,
                 from /home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.cc:1:
/usr/local/include/log4cplus/appender.h:221:22: note: candidate: virtual void log4cplus::Appender::setLayout(std::unique_ptr<log4cplus::Layout>)
         virtual void setLayout(std::unique_ptr<Layout> layout);
                      ^
/usr/local/include/log4cplus/appender.h:221:22: note:   no known conversion for argument 1 from 'std::auto_ptr<log4cplus::Layout>' to 'std::unique_ptr<log4cplus::Layout>'
CMakeFiles/QBus.dir/build.make:65: recipe for target 'CMakeFiles/QBus.dir/home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.o' failed
make[2]: *** [CMakeFiles/QBus.dir/home/csb-devops/Desktop/tom/kafkabridge/cxx/util/logger.o] Error 1
make[2]: Leaving directory '/home/csb-devops/Desktop/tom/kafkabridge/cxx/build'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/QBus.dir/all' failed
make[1]: *** [CMakeFiles/QBus.dir/all] Error 2
make[1]: Leaving directory '/home/csb-devops/Desktop/tom/kafkabridge/cxx/build'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dippac** [comment]
> kafkabridge是Linux C++库，不是跨平台的。gitbash只是有一些Linux下常用命令，并不能代表就能模拟Linux编译环境了。
你好，大神，想请教我已经按照提示吧所有的包都装上了，但是 没有成功，报文如上。请问是否需要更换liblog4cplus 的版本是吗？

**Comment by BewareMyPower** [comment]
> > kafkabridge是Linux C++库，不是跨平台的。gitbash只是有一些Linux下常用命令，并不能代表就能模拟Linux编译环境了。
> > 你好，大神，想请教我已经按照提示吧所有的包都装上了，但是 没有成功，报文如上。请问是否需要更换liblog4cplus 的版本是吗？

是的，我们用的log4cplus是1.2.1版本，因为要支持C++11之前的标准。你用的新版本吧，新版本是用的`unique_ptr`，旧版本用的`auto_ptr`（虽然标注为废弃了，但是C++11标准下编译还是能通过的）。
